{
 "title": "PCF Application Monitoring",
 "description": "PCF Application Monitoring by skhupasa@cisco.com",
 "time": { "from": "2019-06-23T15:32:23.454Z", "to": "2019-06-24T03:16:09.018Z" },
 "templating": {
  "list": [
   {
    "name": "NameSpace",
    "label": "NameSpace",
    "query": "label_values(kube_pod_container_status_restarts_total, exported_namespace)"
   },
   {
    "name": "instance",
    "label": "VM",
    "query": "up{component=\"node-exporter\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(kube_node_labels{})by (label_smi_cisco_com_node_type)",
     "legendFormat": "{{label_smi_cisco_com_node_type}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SBI [HTTP] TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(incoming_request_total[1m])) + sum(rate(outgoing_request_total[1m]))"
    },
    {}
   ]
  },
  {
   "title": "Diameter TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(diameter_requests_total{exported_application=~\".*\",command_code=~\".*\"}[1m])>0) "
    }
   ]
  },
  {
   "title": "LDAP TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(message_total{type=\"usd_ldap_query\"}[1m])>0) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Inbound TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "repeat": "release",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inbound_request_total{interface_name=~\".*\",operation_name=~\".*\",result_code=~\".*\"}[1m])>0) by (interface_name,operation_name,result_code)",
     "legendFormat": "{{interface_name}}-{{operation_name}}"
    },
    {
     "expr": "sum(rate(diameter_requests_total{exported_application=~\".*\",command_code=~\".*\"}[1m])>0) by (exported_application,command_code)",
     "legendFormat": "{{exported_application}}-{{command_code}}"
    }
   ]
  },
  {
   "title": "Result Code Wise Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(incoming_request_total{interface_name=~\".*\",operation_name=~\".*\",result_code=~\".*\"}[1m])>0) by (interface_name,operation_name,result_code)",
     "legendFormat": "{{interface_name}}-{{operation_name}}-{{result_code}}"
    },
    {
     "expr": "sum(rate(outgoing_request_total{interface_name=~\".*\",operation_name=~\".*\",result_code=~\".*\"}[1m])>0) by (interface_name,operation_name,result_code)",
     "legendFormat": "{{interface_name}}-{{operation_name}}-{{result_code}}"
    },
    {
     "expr": "sum(rate(diameter_responses_total{exported_application=~\".*\",command_code=~\".*\",result_code=~\".*\"}[1m])) by (exported_application,command_code,result_code)",
     "legendFormat": "{{exported_application}}-{{command_code}}-{{result_code}}"
    }
   ]
  },
  {
   "title": "End to End Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sort(sum(irate(incoming_request_time[1m])) by (operation_name,result_code)  / sum(irate(incoming_request_total[1m])) by (operation_name,result_code))",
     "legendFormat": "{{ operation_name}}-{{result_code}}"
    },
    {
     "expr": "sort(sum(irate(outgoing_request_time[1m])) by (operation_name,result_code)  / sum(irate(outgoing_request_total[1m])) by (operation_name,result_code))",
     "legendFormat": "{{ operation_name}}-{{result_code}}"
    }
   ]
  },
  {
   "title": "Message Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(irate(message_duration_seconds[1m])) by (type)  / sum(irate(message_total[1m])) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Engine Level Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(message_total{component=~\".*\",type!~\".*usd_ldap_query_wait\",status=~\".*\"}[1m])>0) by (component,type,status)",
     "legendFormat": "{{type}}  {{status}}"
    }
   ]
  },
  {
   "title": "PCF Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(irate(action_duration_seconds[1m])) by (type)  / sum(irate(action_total[1m])) by (type))",
     "legendFormat": "{{ type}}"
    }
   ]
  },
  {
   "title": "GRPC Stats",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(irate(action_duration_seconds{type=~\"grpc.*\"}[1m])) by (type)  / sum(irate(action_total{type=~\"grpc.*\"}[1m])) by (type))",
     "legendFormat": "{{ type}}"
    }
   ]
  },
  {
   "title": "GRPC Stats End Point to Engine",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(irate(incoming_rpc_request_time[1m])) by (message_type,result_code)  / sum(irate(incoming_rpc_request_total[1m])) by (message_type,result_code))",
     "legendFormat": "{{ message_type}}-{{result_code}} (engine->ep)"
    },
    {
     "expr": "sort(sum(irate(outgoing_rpc_request_time[1m])) by (message_type,result_code)  / sum(irate(outgoing_rpc_request_total[1m])) by (message_type,result_code))",
     "legendFormat": "{{ message_type}}-{{result_code}} (ep->engine)"
    }
   ]
  },
  {
   "title": " Pod Restart Count - $NameSpace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "repeat": "NameSpace",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{exported_namespace=~\"$NameSpace.*\"})",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": " Pod Restart Count - $NameSpace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{exported_namespace=~\"$NameSpace.*\"})",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": " Pod Restart Count - $NameSpace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{exported_namespace=~\"$NameSpace.*\"})",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": " Pod Restart Count - $NameSpace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{exported_namespace=~\"$NameSpace.*\"})",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": " Pod Restart Count - $NameSpace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{exported_namespace=~\"$NameSpace.*\"})",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": " Pod Restart Count - $NameSpace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{exported_namespace=~\"$NameSpace.*\"})",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg without (cpu)(irate(node_cpu_seconds_total{component=\"node-exporter\",hostname=\"$instance\",mode=~\".*\"}[1m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}